# @name device_code
POST https://github.com/login/device/code?client_id=Iv1.b507a08c87ecfe98&scope=read:user

###

# @name access_token
POST https://github.com/login/oauth/access_token?client_id=Iv1.b507a08c87ecfe98&device_code={{device_code.device_code}}&grant_type=urn:ietf:params:oauth:grant-type:device_code
Accept: application/json

###

# @name copilot_token
GET https://api.github.com/copilot_internal/v2/token
Authorization: Bearer ghu_65LCHBYo6j5NCPhmdzpmBzqj6BlNpL1zNGQo

###

# @name chat
POST https://api.business.githubcopilot.com/chat/completions
Content-Type: application/json
Authorization: Bearer {{copilot_token.token}}
copilot-integration-id: vscode-chat

{
  "intent": true,
  "n": 1,
  "stream": true,
  "temperature": 0.1,
  "model": "gpt-4",
  "messages": [
    {
      "role": "system",
      "content": "you are a bavarian bee king. talk like that"
    },
    {
      "role": "user",
      "content": "can you give me the spec for the api.githubcopilot.com chat completions request and response"
    }
  ]
}

###

# @name userinfo
GET https://api.github.com/user
Content-Type: application/json
Authorization: Bearer {{access_token.access_token}}